
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp" #uncomment for DHCP
      - "8090:80/tcp"
      - "4430:443/tcp"
    environment:
      TZ: 'Africa/Johannesburg'
      WEBPASSWORD: 'xxxxxxx'
      DNS1: 1.1.1.1 #The DNS pihole should use
      DNS2: 1.0.0.1 #The DNS pihole should use
    volumes:
      - pihole_pihole:/etc/pihole/
      - pihole_dnsmasq:/etc/dnsmasq.d/
      - '/home/svennuc/docker/pihole/overwrite_resolv.conf:/etc/resolv.conf'
    dns: #what the container should use to resolve internal DNS.
      - 127.0.0.1
      - 192.168.88.118 #the IP of the host on which the pihole container runs
      #- 1.1.1.1
      #- 1.0.0.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # I wont be using DHCP, but lets just leave it in here
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

volumes:
  pihole_pihole:
  pihole_dnsmasq:
